# See https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/suborg.yml
# for example layout

suborgrepos:
  - '*'

environments:
#  - name: production
#    wait_timer: 0
#    deployment_branch_policy:
#      protected_branches: false
#      custom_branch_policies:
#        - names: ["main"]
#          type: branch
  - name: test
